server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springsercurity?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    password: root
    username: root
